name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: volta-cli/action@v1
      with:
        node-version: 20.12.0
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "{dir}={$(yarn config get cacheFolder)}" >> $GITHUB_OUTPUT
    - name: Restore yarn cache
      uses: useblacksmith/cache@v5
      id: yarn-cache
      with:
        path: |
          ${{ steps.yarn-cache-dir-path.outputs.dir }}
          **/node_modules
        key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
        restore-keys: "yarn-cache-folder-"
    - run: yarn install --frozen-lockfile
    - run: yarn build
      env:
        BASEHUB_TOKEN: ${{ secrets.BASEHUB_TOKEN }}
        BASEHUB_DRAFT: true
        NEXT_PUBLIC_SITE_URL: "https://replay.io"
    - run: yarn playwright:replay
      env:
        NEXT_PUBLIC_SITE_URL: "https://replay.io"
        BASEHUB_TOKEN: ${{ secrets.BASEHUB_TOKEN }}
        REPLAY_API_KEY: ${{ secrets.REPLAY_API_KEY }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
