name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
    - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: 24
        cache: pnpm
    - run: pnpm install --frozen-lockfile
    - run: pnpm build
      env:
        BASEHUB_TOKEN: ${{ secrets.BASEHUB_TOKEN }}
        BASEHUB_DRAFT: true
        NEXT_PUBLIC_SITE_URL: "https://replay.io"
    - run: pnpm playwright:replay
      env:
        NEXT_PUBLIC_SITE_URL: "https://replay.io"
        BASEHUB_TOKEN: ${{ secrets.BASEHUB_TOKEN }}
        REPLAY_API_KEY: ${{ secrets.REPLAY_API_KEY }}
    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
